# .github/workflows/velog-sync.yml
name: Sync Velog GitHub Series Posts

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser markdown requests beautifulsoup4
          
      - name: Sync Posts
        run: python sync_posts.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VELOG_USERNAME: "cheringring"