
name: Sync Velog GitHub Series Posts

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          
      - name: Sync Posts
        run: python sync_posts.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VELOG_USERNAME: "cheringring"

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add posts/
          git commit -m "Update posts from Velog" || echo "No changes to commit"
          git push